{% set version = "1.2.11" %}
{% set buildnumber = 0 %}

package:
    name: mkl_random
    version: {{ version }}

source:
    path: ..

build:
    number: {{buildnumber}}
    script_env:
      - WHEELS_OUTPUT_FOLDER
    ignore_run_exports:
      - blas

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - {{ stdlib('c') }}
    host:
      - python
      - setuptools >=77
      - mkl-devel
      - cython
      - numpy-base
      - pip
      - wheel  >=0.41.3
    run:
      - python
      - {{ pin_compatible('mkl', min_pin="x.x", max_pin="x") }}
      - {{ pin_compatible('numpy', min_pin="x.x", max_pin="x") }}

test:
    commands:
      - pytest --pyargs mkl_random
    requires:
      - pytest
    imports:
      - mkl_random
      - mkl_random.mklrand

about:
    home: http://github.com/IntelPython/mkl_random
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
